---
title: "Vignette of rGMAP package"
author: "Wenbao Yu"
date: "rGMAP version 1.3 <br><br>Updated on `r Sys.Date()`"
output: BiocStyle::html_document
mainfont: Arial
vignette: >
 %\VignetteIndexEntry{rGMAP}
 %\VignetteEngine{knitr::rmarkdown}
 %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = F, message = F,
  comment = "#>"
)
```

# Installation
## Install from Github
```{r}
library(devtools)
install_github('wbaopaul/rGMAP')

```

## Install from source codes
```{r, eval=F}

install.packages('path to rGMAP_1.3.tar.gz', repos = NULL, type = 'source')

```

# Run an example data
> Data from *Rao et al., Cell 2014, A 3D map of the human genome at kilobase resolution reveals principles of chromatin looping*

> KR normalized Hi-C data for IMR90 cell line, on chr15 with resolution 10kb

```{r, fig.height=3, fig.width=15}
library(rGMAP)
hic_rao_IMR90_chr15   
res = rGMAP(hic_rao_IMR90_chr15, resl = 10 * 1000, dom_order = 2)
names(res)

#quickly visualize some hierarchical domains
pp = plotdom(hic_rao_IMR90_chr15, res$hierTads, 5950, 6900, 30, 10)
pp$p2

```





# Run an simulated example
```{r}
set.seed(1)
simu_res = data_simu('poisson-dist-hier')
true_domains = simu_res$hierTads
simu_mat = simu_res$hic_mat
predicted_domains = rGMAP(simu_mat, resl = 1)$hierTads
true_domains
predicted_domains

```
