# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combPeaks <- function(peaks, stat, dist) {
    .Call('_rGMAP_combPeaks', PACKAGE = 'rGMAP', peaks, stat, dist)
}

